version: "3"

services:
  ruby:
    build: ./backend/.
    container_name: ruby-api
    hostname: ruby-server
    tty: true
    environment:
      - NODE_ENV=DEVELOPMENT
      - PORT=8080
    volumes:
      - ./backend/.:/usr/src/app
    ports:
      - 8080:8080
    working_dir: /usr/src/app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  next:
    build: ./frontend/.
    container_name: next-container
    hostname: next-server
    tty: true
    environment:
      - NODE_ENV=DEVELOPMENT
      - PORT=3000
    volumes:
      - ./frontend/app:/usr/src/app
    ports:
      - 3000:3000
      - 9229:9229
    working_dir: /usr/src/app
    command: npm run dev
